"""Authoritative, UI-independent Jump-Up game state package."""

from .actions import GameAction, GameActionType
from .geometry import Bounds, HouseGeometry, Point
from .layouts import LayoutDataError, load_legacy_layout, load_repository_layouts
from .model import (
    ClaimSelectionMode,
    ClaimState,
    GameConfig,
    GamePhase,
    GameState,
    House,
    Layout,
    LayoutType,
    Player,
    RoundState,
    Stone,
    TurnState,
    WinnerState,
)
from .movement import (
    MovementDirection,
    MovementMode,
    MovementState,
    MovementValidationError,
    begin_hopping,
    begin_return,
    can_pickup_stone,
    hop,
    validate_movement_path,
)
from .physics import (
    PhysicsConfig,
    StoneInitialState,
    StonePhysicsState,
    ThrowResult,
    ThrowStatus,
    simulate_throw,
)
from .transition import InvalidTransitionError, TransitionResult, transition

__all__ = [
    "Bounds",
    "ClaimSelectionMode",
    "ClaimState",
    "GameAction",
    "GameActionType",
    "GameConfig",
    "GamePhase",
    "GameState",
    "House",
    "HouseGeometry",
    "InvalidTransitionError",
    "Layout",
    "LayoutDataError",
    "LayoutType",
    "MovementDirection",
    "MovementMode",
    "MovementState",
    "MovementValidationError",
    "PhysicsConfig",
    "Player",
    "Point",
    "RoundState",
    "Stone",
    "StoneInitialState",
    "StonePhysicsState",
    "ThrowResult",
    "ThrowStatus",
    "TransitionResult",
    "TurnState",
    "WinnerState",
    "begin_hopping",
    "begin_return",
    "can_pickup_stone",
    "hop",
    "load_legacy_layout",
    "load_repository_layouts",
    "simulate_throw",
    "transition",
    "validate_movement_path",
]
